server:
    port: 8003

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost

spring:
    application:
        name: api-gateway
        
    cloud:
        gateway:
            routes:
                - id: flight-service
                  uri: lb://flight-service
                  predicates:
                    - Path=/api/flights/**
                #   filters:
                #     - name: CircuitBreaker
                #       args:
                #         name: customer-service  
                #         fallbackuri: forward:/customerServiceFallback

                - id: airport-service
                  uri: lb://airport-service
                  predicates:
                    - Path=/api/airports/**
                #   filters:
                #     - name: CircuitBreaker
                #       args:
                #         name: product-service  
                #         fallbackuri: forward:/productServiceFallback

                - id: passenger-details-service
                  uri: lb://passenger-details-service
                  predicates:
                    - Path=/api/passengers/**
                #   filters:
                #     - name: CircuitBreaker
                #       args:
                #         name: product-service  
                #         fallbackuri: forward:/productServiceFallback

                # user-management-service
                - id: user-management-service
                  uri: lb://user-management-service
                  predicates:
                    - Path=/**
                #   filters:
                #     - name: CircuitBreaker
                #       args:
                #         name: product-service  
                #         fallbackuri: forward:/productServiceFallback

                - id: booking-details
                  uri: lb://booking-details
                  predicates:
                    - Path=/api/bookings/**
                #   filters:
                #     - name: CircuitBreaker
                #       args:
                #         name: product-service  
                #         fallbackuri: forward:/productServiceFallback

                - id: check-in-service
                  uri: lb://check-in-service
                  predicates:
                    - Path=/api/checkin**
                #   filters:
                #     - name: CircuitBreaker
                #       args:
                #         name: product-service  
                #         fallbackuri: forward:/productServiceFallback

# hystrix:
#     command:
#         fallbackcmd:
#             execution:
#                 isolation:
#                     thread:
#                         timeoutInMillieseconds: 5000

# management:
#     endpoints:
#         web:
#             exposure:
#                 include: hystrix.stream